#@ load("@ytt:data", "data")
#@ load("@ytt:base64", "base64")
---  
apiVersion: v1
kind: Secret
metadata:
  name: musicstore
  namespace: #@ "concourse-{}".format(data.values.common.team)
type: Opaque
data:
  host: #@ base64.encode(data.values.musicstore.host)
  project: #@ base64.encode(data.values.common.team)
  stagingPrefix: #@ base64.encode(data.values.musicstore.stagingPrefix)
  stagingDomain: #@ base64.encode(data.values.musicstore.stagingDomain)
  service-image: #@ base64.encode(data.values.musicstore.serviceImage)
  ui-image: #@ base64.encode(data.values.musicstore.uiImage)
  order-image: #@ base64.encode(data.values.musicstore.orderImage)
  cart-image: #@ base64.encode(data.values.musicstore.cartImage)
  tbsNamespace: #@ base64.encode(data.values.musicstore.tbs.namespace)
  wavefrontApplicationName: #@ base64.encode(data.values.musicstore.wavefront.applicationName)
  wavefrontUri: #@ base64.encode(data.values.musicstore.wavefront.uri)
  wavefrontApiToken: #@ base64.encode(data.values.musicstore.wavefront.apiToken)
  wavefrontDeployEventName: #@ base64.encode(data.values.musicstore.wavefront.deployEventName)
  configRepo: #@ base64.encode(data.values.musicstore.configRepo)
  codeRepo: #@ base64.encode(data.values.musicstore.codeRepo)
  infraRepo: #@ base64.encode(data.values.musicstore.infraRepo)
